routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/')->name('home');
Route::redirect('/', '/posts');

//region POSTS Routes
// CRUD routes
Route::resource('posts', 'PostController');

Route::post('/posts/{post}/likes/count', 'LikeController@count')
    ->name('posts.likes.count');
Route::post('/posts/{post}/is_liked', 'LikeController@isLiked')
    ->name('posts.likes.is_liked');
Route::post('/posts/like/{post}', 'LikeController@like')
    ->name('posts.like')
    ->middleware('auth');

Route::name('comments.')
    ->prefix('comments')
    ->middleware('auth')
    ->group(function () {

        Route::post('/', 'CommentController@store')
            ->name('store');
        Route::delete('/{comment}', 'CommentController@destroy')
            ->name('destroy');

    });
//endregion

Route::get('/profile/{user}', 'ProfileController@show')->name('profile.show');

app/Models/Comment.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{

    protected $fillable = [
        'user_id', 'post_id', 'content'
    ];

    function user() {
        return $this->belongsTo(User::class);
    }

    function post() {
        return $this->belongsTo(Post::class);
    }

}

app/Models/Like.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Like extends Model
{
    protected $fillable = [
        'user_id', 'post_id'
    ];

    function user() {
        return $this->belongsTo(User::class);
    }

    function post() {
        return $this->belongsTo(Post::class);
    }

}

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Traits\HasComments;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasComments;

    protected $fillable = [
        'title', 'content', 'user_id'
    ];

    function user() {
        return $this->belongsTo(User::class);
    }

    function likes() {
        return $this->hasMany(Like::class);
    }

}

app/Models/Traits/HasComments.php
<?php


namespace App\Models\Traits;


use App\Models\Comment;

trait HasComments
{

    function comments() {
        return $this->hasMany(Comment::class)->latest();
    }

}

app/User.php
<?php

namespace App;

use App\Models\Like;
use App\Models\Post;
use App\Models\Traits\HasComments;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, HasComments;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    function posts() {
        return $this->hasMany(Post::class);
    }

    function likes() {
        return $this->hasMany(Like::class);
    }

}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\User;
use Illuminate\Http\Request;
use function auth;
use function redirect;

class CommentController extends Controller
{

    function store(Request $request) {

        $request->validate([
            'content' => 'required',
            'post_id' => 'required'
        ]);

        $data = $request->except('_token');

        /** @var User $user */
        $user = auth()->user();
        $comment = $user->comments()->create($data);

        return redirect()->back();
    }

    function destroy(Comment $comment) {
        $this->authorize('delete', $comment);

        $comment->delete();
        return redirect()->back();
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{

    public function __construct()
    {
    }

    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LikeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Like;
use App\Models\Post;
use Illuminate\Http\Request;
use function auth;
use function optional;

class LikeController extends Controller
{

    function count(Post $post) {
        return [
            'count' => $post->likes->count()
        ];
    }

    protected function hasLike(Post $post) {
        $userId = optional(auth()->user())->id;
        return $post->likes()
            ->where('user_id', $userId)
            ->first();
    }

    function isLiked(Post $post) {
        return [
            'is_liked' => $this->hasLike($post) !== null
        ];
    }

    function like(Post $post) {

        $userId = auth()->user()->id;

        if ($like = $this->hasLike($post))
            $like->delete();
        else
            $post->likes()->create(['user_id' => $userId]);

        return [
            'status' => 200
        ];
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use function dd;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function index()
    {
        return view('posts.index', [
            'title' => 'Стена',
            'posts' => Post::all()
        ]);
    }

    public function create()
    {
        return view('posts.form', [
            'title' => 'Новый пост'
        ]);
    }

    protected function rules() {
        return [
            'title' => 'required|min:5',
            'content' => 'required|min:10'
        ];
    }

    public function store(Request $request)
    {
        $request->validate($this->rules());

        $data = $request->except('_token');

        /** @var \App\User $user */
        $user = auth()->user();
        $post = $user->posts()->create($data);

        return redirect()->route('posts.show', $post);
    }

    public function show(Post $post)
    {
        return view('posts.show', [
            'title' => $post->title,
            'post' => $post
        ]);
    }

    public function edit(Post $post)
    {
        $this->authorize('update', $post);

        return view('posts.form', [
            'title' => 'Изменить ' . $post->title,
            'post' => $post
        ]);
    }

    public function update(Request $request, Post $post)
    {
        $this->authorize('update', $post);
        $request->validate($this->rules());

        $data = $request->except(['_token', '_method']);
        $post->fill($data);
        $post->save();

        return redirect()->route('posts.show', $post);
    }

    public function destroy(Post $post)
    {
        $this->authorize('delete', $post);
        $post->delete();
        return redirect()->route('posts.index');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class ProfileController extends Controller
{

    function show(User $user) {
        return view('profile.show', [
            'user' => $user,
            'posts' => $user->posts,
            'comments' => $user->comments,
            'likes' => $user->likes
        ]);
    }

}

resources/views/_partials/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ route('home') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{{ route('posts.index') }}" class="nav-link">Стена</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else

                    <li class="nav-item">
                        <a href="{{ route('profile.show', auth()->user()) }}" class="nav-link">Профиль</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                  style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<h1>
    {{ app()->getLocale() }}
</h1>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{$title ?? ''}} @if($title ?? false)~@endif {{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

<div id="app">

    @include('_partials.navbar')

    <main class="container py-4">
        @yield('content')
    </main>

</div>

</body>
</html>

resources/views/posts/_partials/actions.blade.php
<?php

use Illuminate\Support\Str;

$id = Str::random(10);
?>

<div class="mb-3 btn-group btn-group-sm">

    @if (optional(auth()->user())->can('update', $post))
        <a class="btn btn-info" href="{{ route('posts.edit', $post) }}">
            Изменить
        </a>
    @endif

    @if (optional(auth()->user())->can('delete', $post))
        <a class="btn btn-danger" id="{{ $id }}" href="{{ route('posts.destroy', $post) }}" data-target="delete-{{ $id }}">
            Удалить
        </a>
    @endif

</div>

@if (optional(auth()->user())->can('delete', $post))

    <form id="delete-{{ $id }}" action="{{ route('posts.destroy', $post) }}" method="POST" class="d-none">
        @csrf
        @method('DELETE')
    </form>

    <script>
        let link = document.getElementById('{{ $id }}');
        if (link) {
            let id = link.dataset.target;
            link.addEventListener('click', function (event) {
                event.preventDefault();
                let form = document.getElementById(id);
                form.submit();
            });
        }
    </script>

@endif

resources/views/posts/_partials/comment.blade.php
<?php

use Illuminate\Support\Str;

$id = Str::random();

?>

<div class="card mb-3 @if($active ?? false) bg-secondary text-white @endif">

    @if ($post ?? false)
    <a href="{{ route('posts.show', $comment->post) }}" class="card-header">{{ $comment->post->title }}</a>
    @endif

    <div class="card-body">
        {{ $comment->content }}
    </div>

    <small class="card-footer d-flex align-items-center">

        <span>{{$comment->user->name}}</span>
        <span class="ml-auto">{{ $comment->created_at }}</span>

        @if($comment->user_id == optional(auth()->user())->id)

            <a href="{{ route('comments.destroy', $comment) }}"
               class="btn btn-outline-danger border-0 btn-sm ml-2"
               id="comment-delete-{{ $id }}"
               data-target="comment-delete-{{$comment->id}}">
                Удалить
            </a>
            <form id="comment-delete-{{$comment->id}}" action="{{ route('comments.destroy', $comment) }}"
                  method="POST">
                @csrf @method('DELETE')
            </form>

        @endif

    </small>

</div>

@if($comment->user_id == optional(auth()->user())->id)
<script>
    let deleteLink = document.getElementById('comment-delete-{{ $id }}');
    deleteLink.addEventListener('click', function (event) {
        event.preventDefault();
        let target = deleteLink.dataset.target;
        let form = document.getElementById(target);
        form.submit();
    });
</script>
@endif

resources/views/posts/_partials/comment_form.blade.php
<form action="{{ route('comments.store') }}" method="POST" class="mb-3">

    @csrf

    <input type="hidden" name="post_id" value="{{ $post->id }}">
    <label for="content">Комментарий</label>

    @error('content')
    <div class="alert alert-danger mb-3">
        Ты должен написать комментарий. А не отправлять в пустую :(
    </div>
    @enderror

    <textarea name="content" id="content" class="form-control" placeholder="Ваш комментарий..."></textarea>

    <div>
        <button class="btn btn-secondary mt-2 btn-sm">Отправить</button>
    </div>

</form>

resources/views/posts/_partials/comments_block.blade.php
@forelse($post->comments as $comment)

    @component('posts._partials.comment', [
        'comment' => $comment,
        'active' => $comment->user_id === optional(auth()->user())->id
    ])@endcomponent

@empty

    <div class="alert alert-secondary">
        Пока нет комментариев. Будь первым!
    </div>

@endforelse

resources/views/posts/_partials/like_button.blade.php
<?php

use Illuminate\Support\Str;

$id = Str::random();
?>

<div class="d-flex">
    <button id="like-{{ $id }}" class="btn ml-auto" @if(!auth()->check()) disabled @endif>
        &#x1F90D; <span class="count"></span>
    </button>
</div>

<script>

    function updateLikesCount(el) {
        axios.post( '{{ route('posts.likes.count', $post) }}' ).then(function (res) {
            let count = res.data['count'];
            let span = el.querySelector('span');
            span.innerHTML = count;
        });
    }

    function checkIsLiked(el) {
        axios.post( '{{ route('posts.likes.is_liked', $post) }}' ).then(function (res) {
            let is_liked = res.data['is_liked'];

            if (is_liked) {
                el.classList.remove('btn-secondary');
                el.classList.add('btn-danger');
            } else {
                el.classList.add('btn-secondary');
                el.classList.remove('btn-danger');
            }
        });
    }

    let likeBtn = document.getElementById('like-{{ $id }}');

    window.onload = function() {
        updateLikesCount(likeBtn);
        checkIsLiked(likeBtn);
    };

    likeBtn.addEventListener('click', function () {

        axios.post( '{{ route('posts.like', $post) }}' ).then(function (response) {
            let data = response.data;

            if (data.status === 200) {
                updateLikesCount(likeBtn);
                checkIsLiked(likeBtn);
            }

        });

    });

</script>

resources/views/posts/_partials/post_block.blade.php
<div class="card card-body mb-3">
    <p class="text-muted">
        Автор:
        <a href="{{ route('profile.show', $post->user) }}">{{ $post->user->name }}</a>
    </p>
    <h1>{{ $post->title }}</h1>
    <p class="lead">{{ $post->content }}</p>

    {{ $slot }}

</div>

resources/views/posts/form.blade.php
<?php
$update = isset($post);
?>

@extends('layouts.app')

@section('content')
    <h1>{{ $title }}</h1>
    <form action="{{ $update ? route('posts.update', $post) : route('posts.store') }}" method="POST" class="card card-body">
        @csrf
        @if ($update)
        @method('PUT')
        @endif
        <div class="form-group">
            <label for="title">Заголовок <span class="text-danger">*</span></label>
            <input type="text"
                   name="title"
                   id="title"
                   class="form-control @error('title') is-invalid @enderror"
                   placeholder="Введите заголовок..."
                   value="{{ old('title') ?? ($post->title ?? '') }}">
        @error('title')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
        </div>

        <div class="form-group">
            <label for="content">Пост <span class="text-danger">*</span></label>
            <textarea name="content"
                      id="content"
                      class="form-control @error('content') is-invalid @enderror"
                      placeholder="Расскажите что-нибудь интресное...">{{ old('content') ?? ($post->content ?? '') }}</textarea>
        @error('content')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
        </div>

        <div>
            <button class="btn btn-success">{{ $update ? 'Обновить' : 'Добавить' }}</button>
        </div>

    </form>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex align-items-center">
        <h1>Стена</h1>
    @if (auth()->check())
        <a href="{{ route('posts.create') }}" class="btn btn-success ml-auto">
            Создать пост
        </a>
    @endif
    </div>

@forelse($posts as $post)
    <a href="{{ route('posts.show', $post) }}" class="mb-3 card card-body d-flex flex-row align-items-center">
        <h4 class="mb-0">{{ $post->title }}</h4>
        <div class="text-muted ml-auto">
            Автор: {{ $post->user->name }}
        </div>
    </a>
@empty
    <div class="alert alert-secondary">
        Постов пока нет...
    </div>
@endforelse

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')

    @if (auth()->check())

        @component('posts._partials.actions', [ 'post' => $post ])@endcomponent

    @endif

    @component('posts._partials.post_block', ['post' => $post])

        @component('posts._partials.like_button', ['post' => $post])@endcomponent

    @endcomponent

    @if (auth()->check())

        @component('posts._partials.comment_form', [ 'post' => $post ])@endcomponent

    @endif

    @component('posts._partials.comments_block', [ 'post' => $post ])@endcomponent


@endsection